#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyroma
Version  : 2.4
Release  : 3
URL      : https://files.pythonhosted.org/packages/1d/e4/540694eb7116c1557244f3d5c656673cea48674cb40759a78bf7bbc14c47/pyroma-2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/1d/e4/540694eb7116c1557244f3d5c656673cea48674cb40759a78bf7bbc14c47/pyroma-2.4.tar.gz
Summary  : Test your project's packaging friendliness
Group    : Development/Tools
License  : MIT
Requires: pyroma-bin
Requires: pyroma-python3
Requires: pyroma-python
Requires: docutils
Requires: setuptools
Requires: zope.event
BuildRequires : buildreq-distutils3
BuildRequires : docutils
BuildRequires : setuptools
BuildRequires : zope.event

%description
======
        
        Pyroma rhymes with aroma, and is a product aimed at giving a rating of how well
        a Python project complies with the best practices of the Python packaging
        ecosystem, primarily PyPI, pip, Distribute etc, as well as a list of issues that
        could be improved.
        
        The aim of this is both to help people make a project that is nice and usable,
        but also to improve the quality of Python third-party software, making it easier
        and more enjoyable to use the vast array of available modules for Python.
        
        It's written so that there are a library with methods to call from Python, as
        well as a script, also called pyroma.

%package bin
Summary: bin components for the pyroma package.
Group: Binaries

%description bin
bin components for the pyroma package.


%package python
Summary: python components for the pyroma package.
Group: Default
Requires: pyroma-python3 = %{version}-%{release}

%description python
python components for the pyroma package.


%package python3
Summary: python3 components for the pyroma package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyroma package.


%prep
%setup -q -n pyroma-2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538620493
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyroma

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
