#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyroma
Version  : 2.5
Release  : 4
URL      : https://files.pythonhosted.org/packages/84/88/cc7ff1ec88e74dfde44e6bf529f5af5161a75edc01309e89ea687ff286fa/pyroma-2.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/84/88/cc7ff1ec88e74dfde44e6bf529f5af5161a75edc01309e89ea687ff286fa/pyroma-2.5.tar.gz
Summary  : Test your project's packaging friendliness
Group    : Development/Tools
License  : MIT
Requires: pyroma-bin = %{version}-%{release}
Requires: pyroma-license = %{version}-%{release}
Requires: pyroma-python = %{version}-%{release}
Requires: pyroma-python3 = %{version}-%{release}
Requires: docutils
Requires: setuptools
Requires: zope.event
BuildRequires : buildreq-distutils3
BuildRequires : docutils
BuildRequires : setuptools
BuildRequires : zope.event

%description
pyroma
======
Pyroma rhymes with aroma, and is a product aimed at giving a rating of how well
a Python project complies with the best practices of the Python packaging
ecosystem, primarily PyPI, pip, Distribute etc, as well as a list of issues that
could be improved.

%package bin
Summary: bin components for the pyroma package.
Group: Binaries
Requires: pyroma-license = %{version}-%{release}

%description bin
bin components for the pyroma package.


%package license
Summary: license components for the pyroma package.
Group: Default

%description license
license components for the pyroma package.


%package python
Summary: python components for the pyroma package.
Group: Default
Requires: pyroma-python3 = %{version}-%{release}

%description python
python components for the pyroma package.


%package python3
Summary: python3 components for the pyroma package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyroma package.


%prep
%setup -q -n pyroma-2.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559410192
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyroma
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/pyroma/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyroma

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyroma/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
